name: Build and Deploy Flask App

on:
  release:
    types:
      - prereleased

jobs:
  build:
    runs-on: ubuntu-latest
    name: Build and Deploy Flask App
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Get the version
        id: get_version
        run: echo "VERSION=${GITHUB_REF##*/}" >> $GITHUB_OUTPUT

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build, tag, and push Docker image
        uses: docker/build-push-action@v6
        with:
          push: true
          tags: ${{ secrets.REGISTRY_HOST }}/${{ secrets.REGISTRY_REPO_NAME }}:flask-app-${{ steps.get_version.outputs.VERSION }}
